print("Welcome")
f=float(input("Enter degrees in Fahrenheit\n"))
c=round(((f-32)*(5/9)),2)
k =round((c+273.15),2)
print("Degrees in Fahrenheit:",f)
print("Degrees in Celcius:",c)
print("Degrees in Kelvin:",k)
